### ISSUE TITLE
template name through configration

### ISSUE THREAD

**Issue by bsr203** [lcaballero/genfront#1]
Hi,

Thanks for this project. One suggestion

```
func (p *FieldsProcessor) Render() (*template.Template, error) {
    tpl,err := Asset("struct_sql_tomap.fm")
    if err != nil {

```

Is it possible to read the template through the `go generate` comment line. This may help to use alternate templates.

In the same vein, do we need different sub commands like `fields`, `front`, or should it just be a single command which reads a template (which may also include a front section).

thanks
bsr

**Comment by lcaballero** [comment]
I updated things so that a file could be specified.  See the normal CLI usage --template.  I think this will work the way you suggested, but I only just got the first draft working.  My hope is to turn genfront into a command for several simple go:generate use cases.  Generalizing like you suggested was part of the vision, but had to come later when I got more time.

**Comment by bsr203** [comment]
thanks for the response. I do not have use of this feature anymore, so please close the issue whenever you feel like. I learned a lot from your code , thank you.
